### ISSUE TITLE
Local Euler Angles on Mobile

### ISSUE THREAD

**Issue by Sylfschiffer** [yasirkula/UnityRuntimeInspector#10]
Hey, I've been using the inspector to position AR objects spawned from markers properly. I would need to use the local euler rotation field to do that propery, but I can't see it on mobile. However, it is visible in the unity editor play mode.

Any ideas on how to make it appear on mobile ?

Thanks !

**Comment by yasirkula** [comment]
If you are using IL2CPP, it is possible that localEulerAngles gets stripped by the engine code stripping functionality. Try using localEulerAngles in your code like this:

```csharp
void Start()
{
    var dummyVar = transform.localEulerAngles;
}
```

Also see: https://usingtheirs.github.io/2018/10/29/Preserving-Unity-Engine-Classes-against-IL2CPP-Byte-Code-Stripping/

**Comment by Sylfschiffer** [comment]
That absolutely solved it, I completely forgot about code stripping.

Thanks for the quick answer !
