### ISSUE TITLE
Multiple Selection

### ISSUE THREAD

**Issue by agandia** [yasirkula/UnityRuntimeInspector#11]
Hi, 
First impressive plugin you made, congratulations.

I am working on a pseudoeditor within Unity's editor, including the cross referencing feature of clicking one object on the scene and having it selected on the hierarchy and vice-versa (hierarchy to scene). That much I managed to do.
Now I am stuck with multiple selections, I dug a bit around RuntimeHierarchy currentSelection and I found out that UnityEditor.Selection.activeTransform does not handle Transform arrays but I could, in theory, use UnityEditor.Selection.objects, I am just running into a bunch of nullreferenceexceptions while adapting the code.

Is this a feature you considered in the past? can it be done? I could use some insight on how to do it.

**Comment by yasirkula** [comment]
There is not much use for multi selection in RuntimeHierarchy since RuntimeInspector doesn't support exposing multiple objects at once, so I'm not planning to add this feature at the moment.

**Comment by agandia** [comment]
Thank you for the quick response.
I will try to fiddle around, see if I can get at least the Hierarchy to show multiple selected objects.

**Comment by yasirkula** [comment]
Feature added in https://github.com/yasirkula/UnityRuntimeInspector/commit/52a8a2548e4daf5dac3c6aa1a624e610699f5491. Note that only RuntimeHierarchy supports multi-selection.

**Comment by D4KU** [comment]
Do you have any plans to make the inspector support it as well? :)

**Comment by yasirkula** [comment]
I don't have the courage to do it in the short term 😂
