### ISSUE TITLE
Allow Inspected GameObject dropdown to be hidden

### ISSUE THREAD

**Issue by Flavelius** [yasirkula/UnityRuntimeInspector#12]
By default the inspected GameObject (when using the RuntimeHierarchy) displays the GameObject with name as a dropdown that can be collapsed.
It would be nice to have an option to make it expanded by default and the dropdown hidden.

**Comment by yasirkula** [comment]
Added feature in https://github.com/yasirkula/UnityRuntimeInspector/commit/fa012110fd3d7ad60bef6d6b721f00dd019f3dab
