### ISSUE TITLE
Change root node of Runtime hierarchy

### ISSUE THREAD

**Issue by saravanan2020** [yasirkula/UnityRuntimeInspector#13]
Hi
    Runtime hierarchy lists all the items from the scene. But i need to change the Root node of runtime hierarchy to a specific gameobject that i want. how to do it. where to change that in code?
Thanks.
By
S

**Comment by yasirkula** [comment]
You can disable RuntimeHierarchy's "Expose Unity Scenes" property from the inspector and then add a PseudoSceneSourceTransform component to the specific GameObject.

**Comment by saravanan2020** [comment]
Thanks.  I will try this.
