### ISSUE TITLE
Multiselect in RuntimeHierarchy

### ISSUE THREAD

**Issue by saravanan2020** [yasirkula/UnityRuntimeInspector#14]
Hi,
       Thanks for quick reply. Is runtime hierarchy supports Multiselection of nodes?  if it is, please reply me how to do it. if its not implemented yet, please add that feature to Runtime Hierarchy. it will be fantastic.

Thanks.
By
S.

**Comment by yasirkula** [comment]
Hello, please see: https://github.com/yasirkula/UnityRuntimeInspector/issues/11

**Comment by saravanan2020** [comment]
Thank you for quick reply
