### ISSUE TITLE
Shows only needed properties in runtime inspector

### ISSUE THREAD

**Issue by saravanan2020** [yasirkula/UnityRuntimeInspector#18]
Hi,
         How to add only needed properties of a selected gameobject to runtime inspector. 
Thanks.
By
S

**Comment by yasirkula** [comment]
Please see **Hidden Variables** and **Exposed Variables**: https://github.com/yasirkula/UnityRuntimeInspector#d1-inspector

**Comment by saravanan2020** [comment]
Thanks for quick reply
