### ISSUE TITLE
Numerical display error

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityRuntimeInspector#21]
![image](https://user-images.githubusercontent.com/50401776/84730089-dbd8e980-afc7-11ea-9bc2-135434c154eb.png)
![image](https://user-images.githubusercontent.com/50401776/84730271-4a1dac00-afc8-11ea-95db-c0e7208bb912.png)
v1.4.53 unity5.5.6
The value of my script is a decimal, which is displayed as an integer in RuntimeInspector

After importing the plugin, I made these changes 
In order to solve the error report and solve the API that my unity does not have
![](https://user-images.githubusercontent.com/50401776/84731305-0bd5bc00-afcb-11ea-8748-db5653a0ca5b.png)
![](https://user-images.githubusercontent.com/50401776/84731120-733f3c00-afca-11ea-9cda-6363aee0fc00.png)

**Comment by ShenKang4181** [comment]
After importing the plugin, I made these changes
In order to solve the error report and solve the API that my unity does not have
![image](https://user-images.githubusercontent.com/50401776/84731120-733f3c00-afca-11ea-9cda-6363aee0fc00.png)
![image](https://user-images.githubusercontent.com/50401776/84731305-0bd5bc00-afcb-11ea-8748-db5653a0ca5b.png)

**Comment by yasirkula** [comment]
Thank you for the 5.5.6 feedback. I'm aware of the numerical value issue; AFAIK it happens on cultures that use ',' (comma) instead of '.' (period) as decimal separator. Unity's InputField doesn't accept ',' (comma) in number fields. I'll try to resolve this issue.

**Comment by ShenKang4181** [comment]
I tried to select the input box, click on the blank space to cancel the selection, and then select the input box again, the decimal point actually appeared miraculously




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Süleyman Yasir KULA"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 下午5:31
收件人: "yasirkula/UnityRuntimeInspector"<UnityRuntimeInspector@noreply.github.com&gt;; 
抄送: "申康康"<1284784181@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yasirkula/UnityRuntimeInspector] Numerical display error (#21)





 
感谢您的5.5.6反馈。我知道数值问题；AFAIK发生在使用“，”（逗号）而不是“。”的文化中。（句点）作为小数点分隔符。Unity的InputField在数字字段中不接受'，'（逗号）。我将尝试解决此问题。
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by ShenKang4181** [comment]
Thank you and love you

**Comment by yasirkula** [comment]
Can you unzip the attached archive and import the unitypackage to your project to see if these issues are resolved?
[RuntimeInspector.zip](https://github.com/yasirkula/UnityRuntimeInspector/files/4801119/RuntimeInspector.zip)

**Comment by ShenKang4181** [comment]
Yes, my problem has been solved, and now the value is displayed normally, thank you, love you yasirkula

**Comment by ShenKang4181** [comment]
Is this a special version for me?

**Comment by yasirkula** [comment]
I'll update the repository, as well. I just wanted make sure beforehand that the issue is resolved 😃

**Comment by ShenKang4181** [comment]
😃😃😃😃😃😃😃😃😃😃😃😃😃😃
