### ISSUE TITLE
Dropdown's item height ignores skins

### ISSUE THREAD

**Issue by Deepscorn** [yasirkula/UnityRuntimeInspector#22]
Thank you very much with the plugin! It's great!

Have one issue: dropdown's item height ignores skins. This results in field being too small and text not seen in our setup. See screenshot.

I use custom skin to make texts not be too small when RuntimeInspector is put on our game canvas. (I increased font size, line height and indent amount in three times).

PS As a workaround, can use standalone canvas for RuntimeInspector

![2020-07-05 01_08_12-SuperCity - MainScene - Android - Unity 2019 3 2f1 Personal  PREVIEW PACKAGES IN](https://user-images.githubusercontent.com/961834/86521805-064af380-be5e-11ea-8861-8325d0f2692a.png)

**Comment by yasirkula** [comment]
Will resolve it as soon as possible.
