### ISSUE TITLE
IL2CPP Compatibility

### ISSUE THREAD

**Issue by Bit00009** [yasirkula/UnityRuntimeInspector#28]
Hello yasirkula,
I just noticed **UnityRuntimeInspector** doesn't work properly with IL2CPP build.
For an example In unity editor I have a light in the scene, when I select the light in inspector all of light component parameters are exposed, color ,intensity and etc.
But in IL2CPP build the only thing gets exposed is Enabled and Bake Index.
I guess it's because you use .net reflection to extract fields but when it gets converted to C++ it can't be working the same way.
Do you have any solution for this or do you have plans to support IL2CPP as well?

Regards,
Ultran

**Comment by yasirkula** [comment]
Please see https://github.com/yasirkula/UnityRuntimeInspector/issues/10

**Comment by Bit00009** [comment]
Thanks!
Should I do this for all the parameters?

**Comment by yasirkula** [comment]
Or you could check this out: https://usingtheirs.github.io/2018/10/29/Preserving-Unity-Engine-Classes-against-IL2CPP-Byte-Code-Stripping/
