### ISSUE TITLE
Name change in Runtime Inspector event

### ISSUE THREAD

**Issue by Kundankmr500** [yasirkula/UnityRuntimeInspector#29]
I am trying to get an event call when the name of gameobject is changed in the Inspector at runtime in Gamview. Can anyone suggest, what event and method I should look for? I have checked in the documentation but unfortunately, I didn't find anything regarding this.

**Comment by yasirkula** [comment]
There isn't a built-in event for it but you can insert your own event into this section of the code: https://github.com/yasirkula/UnityRuntimeInspector/blob/51ecae619d92f68975c68877f698f40862fcd4d6/Plugins/RuntimeInspector/Scripts/RuntimeInspector/Fields/GameObjectField.cs#L30-L38

**Comment by Kundankmr500** [comment]
Thanks, @yasirkula for your suggestion!!
