### ISSUE TITLE
Scriptable Object Support

### ISSUE THREAD

**Issue by fisher-bai** [yasirkula/UnityRuntimeInspector#30]
This asset is really phenomenal. I have a use case where I'd like to be able to edit a Scriptable Object at Runtime. At first glance it didn't look like this was supported, but perhaps I'm missing something? If it's not supported do you have any plans on adding support for Scriptable Objects?

**Comment by yasirkula** [comment]
You can inspect any object that derives from a class via **runtimeInspector.Inspect** function.

**Comment by fisher-bai** [comment]
@yasirkula Wow! That was unbelievably easy. Closing this as resolved.
