### ISSUE TITLE
Compilation error with Input System Package enabled

### ISSUE THREAD

**Issue by ksksni** [yasirkula/UnityRuntimeInspector#42]
**Description of the bug**

Compilation error when using Input System Package
```
error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
```

**Reproduction steps**

1. Set `Project Settings > Player > Other Settings > Active Input Handling` to `Input System Package (New)`
1. Install RuntimeInspector package

**Platform specs**

- Unity version: 2021.1.15f1
- Platform: Windows
- How did you download the plugin: OpenUPM package

**Comment by yasirkula** [comment]
For now, please see: https://github.com/yasirkula/UnityRuntimeInspector#new-input-system-support. I'll probably make the switch easier in the future.
