### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by bleppie** [yasirkula/UnityRuntimeInspector#5]
Hi, fantastic Unity asset!

I would like be able to navigate around the Inspector and Hierarchy using a keyboard. It's fairly easy to add this using Unity's Selectable classes, but the ExpandableInspectorField isn't Selectable, so there isn't a way to navigate to it and expand/collapse it. I'm happy to implement this if you think it's a good idea, and believe there are two ways to do it:

1. Change the current expand/collapse mechanism to a Button (currently it uses a PointerEventListener to catch the mouse click). This seems the more elegant solution, as conceptually it is a button.
2. Subclass PointerEventListener from Selectable, so we can navigate to it and trigger it with the keyboard.

Thoughts?

Cheers,
Brian

**Comment by bleppie** [comment]
Thanks for the quick response and advice.

I use Unity for large projection installations, and I find it easier to use a wireless keyboard while walking around making adjustments rather than a mouse (or trackpad) to first select the input field and then switch to keyboard to enter new values.

I'll go ahead and implement it, and of course it's up to you if you merge or not!

Cheers,
B

**Comment by yasirkula** [comment]
Decided not to add this feature to the plugin. Thanks for the feedback, though!
