### ISSUE TITLE
show select wireframe of selected gui elements

### ISSUE THREAD

**Issue by zxt5105515** [yasirkula/UnityRuntimeInspector#51]
nice plugin! 
sometimes it's hard to tell which object is selected, if plugin can draw select wireframe of selected gui elements ,or a three-axis in the object's position like unity moving tool, it would be very helpful!

**Comment by yasirkula** [comment]
For the time being, I'm happy with having only the Inspector & Hierarchy functionalities. For Transform gizmos, there are other free & paid assets available which you may prefer instead.
