### ISSUE TITLE
Search fallback

### ISSUE THREAD

**Issue by SiMaLaoShi** [yasirkula/UnityRuntimeInspector#52]
After the search is complete, deleting the search content does not return to the original location

**Comment by yasirkula** [comment]
Hi, why did you close this Issue?

**Comment by SiMaLaoShi** [comment]
I can't reproduce it in another version

**Comment by SiMaLaoShi** [comment]
![99ba212a8fae07e40a25fa6e267c3e22](https://user-images.githubusercontent.com/28924681/223941235-6eba34d8-2d2f-47d5-aff4-28a0ab03baee.png)
Let me see if I can reproduce it

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/224019393-8cf0482a-1e7f-46ef-8314-20dd22778ba1.png)
Just manually delete a GameObject and search for it

**Comment by SiMaLaoShi** [comment]
Sorry, can't give you a demo, this error only happens in my project

**Comment by SiMaLaoShi** [comment]
[NewBehaviourScript.txt](https://github.com/yasirkula/UnityRuntimeInspector/files/10931567/NewBehaviourScript.txt)
hi, I made a test script
![image](https://user-images.githubusercontent.com/28924681/224027756-40efde0e-c361-4891-8cbe-ccf701acbe80.png)

**Comment by yasirkula** [comment]
Thank you for sharing your findings! Though I'll fix this issue in the next release, it won't arrive anytime soon so I'd recommend updating [this function](https://github.com/yasirkula/UnityRuntimeInspector/blob/12bd2d85fd5e571756d2783338d9a17706e87263/Plugins/RuntimeInspector/Scripts/RuntimeHierarchy/HierarchyDataRootScene.cs#L29-L32) manually as follows:

```csharp
public override Transform GetChild( int index )
{
	GameObject rootObject = rootObjects[index];
	return rootObject ? rootObject.transform : null;
}
```

**Comment by SiMaLaoShi** [comment]
Good
