### ISSUE TITLE
How to hide certain gameobjects from runtime hierarchy within my scene and pseudoscenes

### ISSUE THREAD

**Issue by hemanth2004** [yasirkula/UnityRuntimeInspector#55]
I would like to hide a certain gameobjects that are descendants of my pseudoscene and all of their children too. How do I do this? (New to raising issues so apologies if this isn't the right place the ask)

**Comment by yasirkula** [comment]
Hi, quoting the documentation:

> You can register to the GameObjectFilter delegate of the hierarchy to hide some objects from the hierarchy (or, you can add those objects to RuntimeInspectorUtils.IgnoredTransformsInHierarchy and they will be hidden from all hierarchies; just make sure to remove them from this HashSet before they are destroyed)

```csharp
runtimeHierarchy.GameObjectFilter = ( Transform obj ) =>
{
    if( obj.CompareTag( "Main Camera" ) )
        return false; // Hide Main Camera from hierarchy
 
    return true;
};
```

**Comment by hemanth2004** [comment]
Ohk Thats helpful thanks! (and sorry!) I love your work, by the way. Big fan.
