### ISSUE TITLE
Hide Certain Components

### ISSUE THREAD

**Issue by MustangF16** [yasirkula/UnityRuntimeInspector#7]
is it possible to hide certain components such as Transform and Rigidbody component, or by default all of the components are hidden and expose certain ones ?

**Comment by yasirkula** [comment]
You can filter the components here: https://github.com/yasirkula/UnityRuntimeInspector/blob/ecc5ffbd6d75d3906809f6480b1f8a5bcd145a50/Plugins/RuntimeInspector/Scripts/RuntimeInspector/Fields/GameObjectField.cs#L97-L101

**Comment by MustangF16** [comment]
Perfect ! Thanks a lot for this top asset !
